

export const RESPONSE = {

   tittle:[
      "Reporte de Venta",
      "Resumen por Operaciones/Empresas"
   ],
   header:[
      {
         name:"Inicializacion",
         action_code:"init"
      },
      {
         name:"Emision",
         action_code:"issue"
      },
      {
         name:"Venta",
         action_code:"sale"
      },
      {
         name:"Recarga",
         action_code:"recharge"
      },
      {
         name:"Transito",
         action_code:"transit"
      },
      {
         name:"Consumo",
         action_code:"consume"
      },
      {
         name:"Remplazo",
         action_code:"replacement"
      },
      {
         name:"Borrado",
         action_code:"erase"
      },
      {
         name:"Terminado",
         action_code:"terminate"
      },
      {
         name:"Bloquear",
         action_code:"block"
      }
   ],
   data:[
      {
         action_code:"recharge",
         company_code:"0000",
         nominal_amount:3.0,
         moment:"01-02-2022",
         count:1
      },
      {
         action_code:"recharge",
         company_code:"1008020200002",
         nominal_amount:16.0,
         moment:"05-02-2022",
         count:4
      },
      {
         action_code:"recharge",
         company_code:"1008020200002",
         nominal_amount:3.0,
         moment:"03-02-2022",
         count:1
      },
      {
         action_code:"issue",
         company_code:"0000",
         nominal_amount:3.0,
         moment:"01-02-2022",
         count:1
      },
      {
         action_code:"issue",
         company_code:"1008020200002",
         nominal_amount:16.0,
         moment:"05-02-2022",
         count:4
      }
   ],
   global_total:[
      {
         nominal_amount_init:0.0,
         nominal_amount_issue:19.0,
         nominal_amount_sale:0.0,
         nominal_amount_recharge:22.0,
         nominal_amount_transit:0.0,
         nominal_amount_consume:0.0,
         nominal_amount_replacement:0.0,
         nominal_amount_erase:0.0,
         nominal_amount_terminate:0.0,
         nominal_amount_block:0.0,
         nominal_amount_total:41.0
      },
      {
         transaction_amount_init:0.0,
         transaction_amount_issue:5.0,
         transaction_amount_sale:0.0,
         transaction_amount_recharge:6.0,
         transaction_amount_transit:0.0,
         transaction_amount_consume:0.0,
         transaction_amount_replacement:0.0,
         transaction_amount_erase:0.0,
         transaction_amount_terminate:0.0,
         transaction_amount_block:0.0,
         transaction_amount_total:11.0
      }
   ],
   Sub_total:{
      "01-02-2022":[
         {
            nominal_amount_init:0.0,
            nominal_amount_issue:3.0,
            nominal_amount_sale:0.0,
            nominal_amount_recharge:3.0,
            nominal_amount_transit:0.0,
            nominal_amount_consume:0.0,
            nominal_amount_replacement:0.0,
            nominal_amount_erase:0.0,
            nominal_amount_terminate:0.0,
            nominal_amount_block:0.0,
            nominal_amount_total:6.0
         },
         {
            transaction_amount_init:0.0,
            transaction_amount_issue:1.0,
            transaction_amount_sale:0.0,
            transaction_amount_recharge:1.0,
            transaction_amount_transit:0.0,
            transaction_amount_consume:0.0,
            transaction_amount_replacement:0.0,
            transaction_amount_erase:0.0,
            transaction_amount_terminate:0.0,
            transaction_amount_block:0.0,
            transaction_amount_total:2.0
         }
      ],
      "03-02-2022":[
         {
            nominal_amount_init:0.0,
            nominal_amount_issue:0.0,
            nominal_amount_sale:0.0,
            nominal_amount_recharge:3.0,
            nominal_amount_transit:0.0,
            nominal_amount_consume:0.0,
            nominal_amount_replacement:0.0,
            nominal_amount_erase:0.0,
            nominal_amount_terminate:0.0,
            nominal_amount_block:0.0,
            nominal_amount_total:3.0
         },
         {
            transaction_amount_init:0.0,
            transaction_amount_issue:0.0,
            transaction_amount_sale:0.0,
            transaction_amount_recharge:1.0,
            transaction_amount_transit:0.0,
            transaction_amount_consume:0.0,
            transaction_amount_replacement:0.0,
            transaction_amount_erase:0.0,
            transaction_amount_terminate:0.0,
            transaction_amount_block:0.0,
            transaction_amount_total:1.0
         }
      ],
      "05-02-2022":[
         {
            nominal_amount_init:0.0,
            nominal_amount_issue:16.0,
            nominal_amount_sale:0.0,
            nominal_amount_recharge:16.0,
            nominal_amount_transit:0.0,
            nominal_amount_consume:0.0,
            nominal_amount_replacement:0.0,
            nominal_amount_erase:0.0,
            nominal_amount_terminate:0.0,
            nominal_amount_block:0.0,
            nominal_amount_total:32.0
         },
         {
            transaction_amount_init:0.0,
            transaction_amount_issue:4.0,
            transaction_amount_sale:0.0,
            transaction_amount_recharge:4.0,
            transaction_amount_transit:0.0,
            transaction_amount_consume:0.0,
            transaction_amount_replacement:0.0,
            transaction_amount_erase:0.0,
            transaction_amount_terminate:0.0,
            transaction_amount_block:0.0,
            transaction_amount_total:8.0
         }
      ]
   },
   Total_by_company:[
      {
         date:"01-02-2022",
         company:"0000",
         nominal_amount_total:6.0,
         transaction_amount_total:2.0
      },
      {
         date:"03-02-2022",
         company:"1008020200002",
         nominal_amount_total:3.0,
         transaction_amount_total:1.0
      },
      {
         date:"05-02-2022",
         company:"1008020200002",
         nominal_amount_total:32.0,
         transaction_amount_total:8.0
      }
   ]
}