export const users = [
    {
       user:{
            username:'empleado01',
            password:'12345678912345678912',
            first_name:'Pepi ',
            last_name : 'Perez',
            email:'pepi@mail.com',
        },
        employee:{
            employee_code:'1',
            company_code:'1234',
            second_name:'Pedrito',
            second_last_name:'Rosa',
            sex:'Masculino',
            personal_id:'V-123456789',
            mobile:'04124563789',
            role: 'Administrador',
            permissions:['view_user'],
            description:'soy un empleado',
            deparment_no:1,
            operator_card:'123456789123',
            active:true
        }
    },
    // {
    //     employee_code: '2',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'J-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: false,
    //     role: 'Administrador',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '3',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'V-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: false,
    //     role: 'Administrador',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '4',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'V-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: false,
    //     role: 'Administrador',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '5',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'J-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: false,
    //     role: 'Administrador',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '6',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'J-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: false,
    //     role: 'Administrador',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '7',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'V-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'supervisor',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '8',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'V-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'Gestor de Flota',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '9',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'V-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'Operador de Mantenimiento',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '10',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'J-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'Conductor',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '11',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'V-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'Conductor',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '12',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'J-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'Conductor',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '13',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'V-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'Conductor',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '14',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'J-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'Conductor',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
    // {
    //     employee_code: '15',
    //     username: 'empleado01',
    //     company_code: '1234',
    //     branch_code: '1234',
    //     first_name: 'Pepi ',
    //     second_name: 'Pedrito',
    //     last_name: 'Perez',
    //     second_last_name: 'Rosa',
    //     sex: 'Masculino',
    //     personal_id: 'V-123456789',
    //     email: 'pepi@mail.com',
    //     mobile: '04124563789',
    //     pwd: '12345678912345678912',
    //     active: true,
    //     role: 'Gestor de Tarifas',
    //     permission: ['view_user'],
    //     description: 'soy un empleado',
    //     created_on: 'new Date ()',
    //     last_update_on: 'new Date ()',
    //     department_no: 1,
    //     operator_card: '123456789123',
    // },
]
