export const stops = [
    {
        stop_code: '1',
        trans_means: 'bus',
        name: 'parada-1',
        abbreviation: 'rta1',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.49562', '-66.84887'],
        },
        municipality_code: '1170001',
        state_code: 'ccs',
        is_public_stop: false,
    },
    {
        stop_code: '2',
        trans_means: 'bus',
        name: 'parada-2',
        abbreviation: 'rta2',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.48386', '-66.85115'],
        },
        municipality_code: '117002',
        state_code: '4567',
        is_public_stop: true,
    },
    {
        stop_code: '3',
        trans_means: 'bus',
        name: 'parada-3',
        abbreviation: 'rta3',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.48299', '-66.84794'],
        },
        municipality_code: '1170006',
        state_code: '24484',
        is_public_stop: true,
    },
    {
        stop_code: '4',
        trans_means: 'bus',
        name: 'parada-4',
        abbreviation: 'rta4',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.478222', '-66.843063'],
        },
        municipality_code: '1170008',
        state_code: '1458',
        is_public_stop: true,
    },
    {
        stop_code: '5',
        trans_means: 'bus',
        name: 'parada-5',
        abbreviation: 'rta5',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.471798', '-66.838707'],
        },
        municipality_code: '59849',
        state_code: '15165',
        is_public_stop: true,
    },
    {
        stop_code: '6',
        trans_means: 'bus',
        name: 'parada-6',
        abbreviation: 'rta6',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.465307', '-66.833405'],
        },
        municipality_code: '15158',
        state_code: '444894',
        is_public_stop: true,
    },
    {
        stop_code: '7',
        trans_means: 'bus',
        name: 'parada-7',
        abbreviation: 'rta7',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.46162', '-66.83017'],
        },
        municipality_code: '546448',
        state_code: '54484',
        is_public_stop: true,
    },
    {
        stop_code: '8',
        trans_means: 'bus',
        name: 'parada-8',
        abbreviation: 'rta8',

        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.475094082442878', '-66.89624279737474'],
        },
        municipality_code: '626262',
        state_code: '1514561',
        is_public_stop: true,
    },
    {
        stop_code: '9',
        trans_means: 'bus',
        name: 'parada-9',
        abbreviation: 'rta9',

        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.5085886142864', '-66.90856754779817'],
        },
        municipality_code: '21515',
        state_code: '2448',
        is_public_stop: true,
    },
    {
        stop_code: '10',
        trans_means: 'bus',
        name: 'parada-10',
        abbreviation: 'rta10',

        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.497601752617085', '-66.91062748432161'],
        },
        municipality_code: '262626',
        state_code: '15612',
        is_public_stop: true,
    },
    {
        stop_code: '11',
        trans_means: 'bus',
        name: 'parada-11',
        abbreviation: 'rta11',

        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.47828544996434', '-66.90063893795015'],
        },
        municipality_code: '54545',
        state_code: '1515615',
        is_public_stop: true,
    },

    {
        stop_code: '12',
        trans_means: 'bus',
        name: 'parada-12',
        abbreviation: 'rta12',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.490754109641697', '-66.91136300010508'],
        },
        municipality_code: '156161',
        state_code: '515156',
        is_public_stop: true,
    },

    {
        stop_code: '13',
        trans_means: 'bus',
        name: 'parada-13',
        abbreviation: 'rta13',

        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.465307', '-66.833405'],
        },
        municipality_code: '5156156',
        state_code: '5151',
        is_public_stop: true,
    },

    {
        stop_code: '14',
        trans_means: 'bus',
        name: 'parada-14',
        abbreviation: 'rt14',
        route: 'plaza venezuela - chacao',
        location: {
            type: 'urbana',
            coordinates: ['10.481234138833441', '-66.9039434194565'],
        },
        municipality_code: '5165165',
        state_code: '454651',
        is_public_stop: true,
    },
]
